# Generated by Django 5.2.1 on 2025-05-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_remove_userpreference_favorite_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='tempo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
