# Generated by Django 5.2.1 on 2025-05-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_alter_userpreference_tempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackrecommendation',
            name='user',
        ),
        migrations.AddField(
            model_name='trackrecommendation',
            name='user_session_key',
            field=models.CharField(default='default_session', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='tempo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user_session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
