# Generated by Django 5.2.1 on 2025-05-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_alter_userpreference_genre_alter_userpreference_mood_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='tempo',
        ),
        migrations.AlterField(
            model_name='trackrecommendation',
            name='user_session_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user_session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
